# Generated by Django 3.2.10 on 2022-03-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=18, default=0, max_digits=100)),
                ('balance_after_transaction', models.DecimalField(decimal_places=18, default=0, max_digits=100)),
                ('transacting_currency', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('off-chain', 'off-chain'), ('on-chain', 'on-chain')], max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
