# Generated by Django 3.2.10 on 2022-03-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
