# Generated by Django 3.2.10 on 2022-03-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20220307_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(default='Bitcoin', max_length=256)),
                ('short_name', models.CharField(default='BTC', max_length=12)),
                ('icon', models.URLField(blank=True, null=True)),
                ('encrypted_private_key', models.TextField(blank=True, null=True)),
                ('mnemonics', models.TextField(blank=True, null=True)),
                ('xpub', models.TextField(blank=True, null=True)),
                ('public_key', models.CharField(blank=True, help_text='address', max_length=256, null=True)),
                ('previous_bal', models.DecimalField(decimal_places=18, default=0, max_digits=100)),
                ('available_bal', models.DecimalField(decimal_places=18, default=0, max_digits=100)),
                ('frozen', models.BooleanField(default=False)),
                ('frozen_bal', models.DecimalField(decimal_places=18, default=0, max_digits=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bitcoin',
                'verbose_name_plural': 'bitcoin',
                'db_table': 'bitcoin',
            },
        ),
    ]
