# Generated by Django 3.2.10 on 2022-05-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20220516_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivation_key', models.IntegerField()),
                ('address_key', models.CharField(max_length=300)),
                ('coin_symbol', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='BitcoinMnemonics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=500, null=True)),
                ('seed_phrase', models.TextField()),
                ('xpub', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bitcoin mnemonics',
                'verbose_name_plural': 'bitcoin mnemonics',
                'db_table': 'bitcoin_mnemonics',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('available_balance', models.CharField(max_length=300)),
                ('account_balance', models.CharField(max_length=300)),
                ('frozen', models.BooleanField(default=False)),
                ('customer_id', models.CharField(max_length=300)),
                ('currency', models.CharField(default='USD', max_length=300)),
                ('ledger_id', models.CharField(max_length=300)),
                ('xpub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.bitcoinmnemonics')),
            ],
            options={
                'verbose_name': 'ledger account',
                'verbose_name_plural': 'ledger accounts',
                'db_table': 'ledger_account',
            },
        ),
        migrations.DeleteModel(
            name='Bitcoin',
        ),
        migrations.AddField(
            model_name='address',
            name='xpub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.bitcoinmnemonics'),
        ),
    ]
