apiVersion: apps/v1
kind: Deployment
metadata:
  name: syarpa-deployment
  labels:
    app: syarpa-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: syarpa-deployment
  template:
    metadata:
      labels:
        app: syarpa-deployment
    spec:
      containers:
      - name: syarpa
        image: registry.digitalocean.com/syarpa/syarpa:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: syarpa
        env:
          - name: PORT
            value: "8002"
        ports:
        - containerPort: 8002
      imagePullSecrets:
        - name: syarpa


---
apiVersion: v1
kind: Service
metadata:
  name: syarpa-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8002
  selector:
    app: syarpa-deployment